nombre: "Hoodie 1"
talla: "X-M-L"
descripcion: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Consequatur architecto dolores eum sed illum amet."
precio: 20
categoria: "Hoddies"
estado: "Promoción"
img1: "/img/hoodie1.jpg"
img2: "/img/hoodie1.jpg"
img3: "/img/hoodie1.jpg"
