backend:
  name: git-gateway
  branch: master

media_folder: "public/img"       # donde se guardan las imágenes
public_folder: "/img"            # ruta accesible desde la web

collections:
  - name: "productos"
    label: "Productos"
    folder: "contenido/productos"   # donde se guardan los YAML
    create: true
    slug: "{{nombre | slugify}}"
    fields:
      - { label: "Nombre", name: "nombre", widget: "string" }
      - { label: "Talla", name: "talla", widget: "string" }
      - { label: "Descripción", name: "descripcion", widget: "string", pattern: ['^.{0,155}$', "La descripción no puede tener más de 155 caracteres"] }
      - { label: "Precio", name: "precio", widget: "number" }
      - { label: "Categoría", name: "categoria", widget: "select", options: ["Hoddies", "Camisetas", "Pantalones"] }
      - { label: "Estado", name: "estado", widget: "select", options: ["Normal", "Promoción", "Nuevo"] }
      - { label: "Imagen1", name: "img1", widget: "image" }
      - { label: "Imagen2", name: "img2", widget: "image" }
      - { label: "Imagen3", name: "img3", widget: "image" }
